baseURL: https://segura.systems/
languageCode: en-us
title: segura.systems

module:
  imports:
  - path: github.com/adityatelange/hugo-PaperMod

theme: github.com/adityatelange/hugo-PaperMod

enableRobotsTXT: true
enableEmoji: true

params:
  defaultTheme: auto

  profileMode:
    enabled: true
    title: Daniel Segura

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/dsegurag"
    - name: github
      url: "https://github.com/dsegurag"
    - name: buymeacoffee
      url: "https://www.buymeacoffee.com/dsegurag"

  assets:
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.pn"
    safari_pinned_tab: "/safari-pinned-tab.svg"
